export const FETCHING_LEAGUE = "FETCHING_LEAGUE";
export const FETCH_LEAGUE_ERROR = "FETCH_LEAGUE_ERROR";
export const FETCH_LEAGUE_SUCCESS = "FETCH_LEAGUE_SUCCESS";
export const FETCHING_LEAGUES = "FETCHING_LEAGUES";
export const FETCH_LEAGUES_ERROR = "FETCH_LEAGUES_ERROR";
export const FETCH_LEAGUES_SUCCESS = "FETCH_LEAGUES_SUCCESS";
